### ISSUE TITLE
Replace emitter drive bjt with correct mos transistor

### ISSUE THREAD

**Issue by korn0055** [korn0055/bean-bag-toss#8]
Tie all gates to same pin on uC (free up pin for receive circuitry power control)

**Comment by NothingButGunpowder** [comment]
BJT transistor updated to MOSFET, BS870.

**Comment by NothingButGunpowder** [comment]
i=C*dv/dt, 50pF max gate cap and 20mA drive means <40ns turn on for 3 devices in parallel.
